# Generated by Django 5.0.6 on 2024-07-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
