# Generated by Django 5.0.6 on 2024-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_floor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='gridx',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='gridy',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
