# Generated by Django 5.0.6 on 2024-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rack_angle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='model_name',
            field=models.CharField(choices=[('cooler', 'Cooler'), ('electrical_panel', 'Electrical Panel'), ('perforated_tile', 'Perforated Tile'), ('rack', 'Rack'), ('raised_floor', 'Raised Floor'), ('solar_panel', 'Solar Panel')], default='rack', max_length=20),
            preserve_default=False,
        ),
    ]
