# Generated by Django 4.2.5 on 2024-08-01 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rack_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('depth', models.FloatField()),
                ('model_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('angle', models.FloatField()),
                ('model_name', models.CharField(choices=[('cooler', 'Cooler'), ('electrical_panel', 'Electrical Panel'), ('perforated_tile', 'Perforated Tile'), ('rack', 'Rack'), ('raised_floor', 'Raised Floor'), ('solar_panel', 'Solar Panel')], max_length=20)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='myapp.floor')),
            ],
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
