# Generated by Django 4.2.5 on 2024-08-01 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_figure_delete_rack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='model_name',
            new_name='figure_name',
        ),
        migrations.RenameField(
            model_name='figure',
            old_name='model_type',
            new_name='figure_type',
        ),
    ]
