# Generated by Django 5.0.6 on 2024-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_model_name_figure_figure_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='site_name',
            field=models.CharField(default='MNS', max_length=50),
            preserve_default=False,
        ),
    ]
