# Generated by Django 5.0.6 on 2024-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_floor_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='rack_id',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
